# Generated by Django 5.1.15 on 2026-03-24 23:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tcc_reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(choices=[('single_report', 'Отдельный отчёт'), ('subscription_monthly', 'Подписка месяц'), ('subscription_annual', 'Подписка год'), ('data_feed', 'Дата-фид'), ('custom', 'Кастомный')], max_length=30, verbose_name='Тип продукта')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (USD)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('included_report_templates', models.ManyToManyField(blank=True, to='tcc_reports.reporttemplate', verbose_name='Включённые шаблоны')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='tcc_reports.report', verbose_name='Отчёт')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ['price_usd'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('paid', 'Оплачен'), ('cancelled', 'Отменён'), ('refunded', 'Возврат')], default='pending', max_length=20, verbose_name='Статус')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма (USD)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачен')),
                ('payment_ref', models.CharField(blank=True, max_length=300, verbose_name='Ссылка на оплату')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tcc_orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='tcc_commerce.product', verbose_name='Продукт')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='Выдан')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Истекает')),
                ('access_type', models.CharField(choices=[('purchase', 'Куплен'), ('subscription', 'Подписка'), ('free', 'Бесплатный'), ('demo', 'Демо'), ('admin', 'Админ')], max_length=20, verbose_name='Тип доступа')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tcc_commerce.order', verbose_name='Заказ')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='tcc_reports.report', verbose_name='Отчёт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступ к отчёту',
                'verbose_name_plural': 'Доступы к отчётам',
                'unique_together': {('user', 'report')},
            },
        ),
    ]
