# Generated by Django 5.1.15 on 2026-04-07 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('hero', 'Hero (большой заголовок)'), ('text', 'Текст (заголовок + абзац)'), ('feature_grid', 'Сетка преимуществ'), ('stats', 'Метрики / цифры'), ('cta', 'Call to action'), ('quote', 'Цитата'), ('image_text', 'Картинка + текст'), ('divider', 'Разделитель'), ('custom_html', 'HTML (для сложных блоков)')], max_length=32)),
                ('eyebrow', models.CharField(blank=True, help_text='Маленький надзаголовок (gold caps)', max_length=120)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('subheading', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True, help_text='Основной текст. Поддерживает переносы строк.')),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='landing/blocks/')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Структурированные данные для feature_grid / stats и т.п.')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
