# Generated by Django 5.1.15 on 2026-04-08 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_contentblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Технический идентификатор: landing, about, solutions…', max_length=100, unique=True)),
                ('title', models.CharField(help_text='Заголовок для админки', max_length=255)),
                ('meta_title', models.CharField(blank=True, help_text='<title> в HTML. Если пусто — берётся title', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='<meta description> для SEO', max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Страница сайта',
                'verbose_name_plural': 'Страницы сайта',
                'ordering': ['slug'],
            },
        ),
        migrations.AlterModelOptions(
            name='advantage',
            options={'ordering': ['order'], 'verbose_name': 'Преимущество', 'verbose_name_plural': 'Преимущества'},
        ),
        migrations.AlterModelOptions(
            name='contactinfo',
            options={'verbose_name': 'Контактная информация', 'verbose_name_plural': 'Контактная информация'},
        ),
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Legacy блок главной', 'verbose_name_plural': 'Legacy блоки главной'},
        ),
        migrations.AlterModelOptions(
            name='herosection',
            options={'verbose_name': 'Hero блок (главная)', 'verbose_name_plural': 'Hero блоки (главная)'},
        ),
        migrations.AlterModelOptions(
            name='metric',
            options={'ordering': ['order'], 'verbose_name': 'Метрика / цифра', 'verbose_name_plural': 'Метрики / цифры'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'ordering': ['order'], 'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='testimonial',
            options={'ordering': ['order'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='body',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='eyebrow',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.CreateModel(
            name='PageSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_key', models.SlugField(blank=True, help_text='Опциональный якорь/id для секции', max_length=80)),
                ('block_type', models.CharField(choices=[('hero', 'Hero — большой заголовок'), ('text', 'Текст — заголовок + абзац'), ('text_image', 'Текст + изображение'), ('feature_grid', 'Сетка преимуществ / features'), ('stats', 'Метрики / цифры'), ('cta', 'Call to action'), ('quote', 'Цитата'), ('bento', 'Editorial bento (карточки)'), ('partners_grid', 'Логотипы партнёров'), ('custom_html', 'Сырой HTML'), ('divider', 'Разделитель')], default='text', max_length=32)),
                ('eyebrow', models.CharField(blank=True, help_text='Маленький надзаголовок (gold caps)', max_length=120)),
                ('heading', models.CharField(blank=True, max_length=255)),
                ('subheading', models.CharField(blank=True, max_length=500)),
                ('body', models.TextField(blank=True, help_text='Основной текст. Поддерживает HTML и переносы строк.')),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_url', models.CharField(blank=True, max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/sections/')),
                ('data', models.JSONField(blank=True, default=dict, help_text='Структурированные данные: items для feature_grid, цифры для stats, и т.д. Пример: [{"label":"Grueopotok","value":"4.5 млн т"}]')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='landing.page')),
            ],
            options={
                'verbose_name': 'Блок страницы',
                'verbose_name_plural': 'Блоки страниц',
                'ordering': ['page', 'order', 'id'],
            },
        ),
    ]
