# Generated by Django 5.1.15 on 2026-04-08 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_page_alter_advantage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('kind', models.CharField(choices=[('статья', 'Статья'), ('интервью', 'Интервью'), ('исследование', 'Исследование'), ('видео', 'Видео'), ('мероприятие', 'Мероприятие'), ('новость', 'Новость')], default='новость', max_length=32, verbose_name='Тип')),
                ('excerpt', models.TextField(blank=True, max_length=600, verbose_name='Краткое описание')),
                ('body', models.TextField(blank=True, verbose_name='Полный текст (HTML)')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Обложка')),
                ('cover_url', models.URLField(blank=True, help_text='Используется если нет загруженной обложки', max_length=1000, verbose_name='URL внешней обложки')),
                ('external_url', models.URLField(blank=True, max_length=1000, verbose_name='Внешняя ссылка (опц.)')),
                ('published_at', models.DateField(verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('show_on_landing', models.BooleanField(default=False, help_text='Один из плавающих блоков hero', verbose_name='Показывать на главной')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Новость сайта',
                'verbose_name_plural': 'Новости сайта',
                'ordering': ['-published_at', 'order', '-id'],
            },
        ),
    ]
