# Generated by Django 5.1.15 on 2026-04-08 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_seed_sitenews'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('article', 'Статья аналитики'), ('partner', 'Партнёр'), ('project', 'Проект'), ('program', 'Программа обучения'), ('report', 'Отчёт'), ('team', 'Член команды'), ('expert', 'Эксперт')], db_index=True, max_length=32, verbose_name='Категория')),
                ('subcategory', models.CharField(blank=True, help_text="Напр. 'international'/'education' для партнёров, 'middle_corridor'/'research' для проектов", max_length=80, verbose_name='Подкатегория')),
                ('slug', models.SlugField(blank=True, max_length=200, verbose_name='Slug')),
                ('title', models.CharField(max_length=300, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=300, verbose_name='Подзаголовок')),
                ('description', models.TextField(blank=True, max_length=1500, verbose_name='Описание')),
                ('body', models.TextField(blank=True, verbose_name='Полный текст (HTML)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='site_items/', verbose_name='Изображение/лого')),
                ('image_url', models.URLField(blank=True, max_length=1000, verbose_name='URL изображения')),
                ('link_url', models.URLField(blank=True, max_length=1000, verbose_name='Ссылка')),
                ('tag', models.CharField(blank=True, max_length=80, verbose_name='Тег/бейдж')),
                ('status', models.CharField(blank=True, help_text="Напр. 'активный'/'в разработке'", max_length=40, verbose_name='Статус')),
                ('data', models.JSONField(blank=True, default=dict, help_text="Метрики, доп. поля: {'metrics': ['4.5 млн т','EUR 18.5 млрд']}", verbose_name='Доп. данные')),
                ('order', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Материал сайта',
                'verbose_name_plural': 'Материалы сайта',
                'ordering': ['category', 'order', '-id'],
                'indexes': [models.Index(fields=['category', 'subcategory', 'order'], name='landing_sit_categor_31bea6_idx')],
            },
        ),
    ]
