# Generated by Django 5.1.15 on 2026-04-08 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_seed_siteitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteitem',
            name='category',
            field=models.CharField(choices=[('article', 'Статья аналитики'), ('partner', 'Партнёр'), ('project', 'Проект'), ('program', 'Программа обучения'), ('report', 'Отчёт'), ('team', 'Член команды'), ('expert', 'Эксперт'), ('solution', 'Направление / решение')], db_index=True, max_length=32, verbose_name='Категория'),
        ),
    ]
