# Generated by Django 5.1.15 on 2026-04-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0009_seed_experts_solutions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('message', models.TextField(blank=True, verbose_name='Сообщение')),
                ('source', models.CharField(default='contacts', help_text='contacts / landing / bot', max_length=40, verbose_name='Источник')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
