# Generated by Django 5.1.15 on 2026-06-29 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_contact_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteitem',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
