# Generated by Django 5.1.15 on 2026-03-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_videotimestamp_videoprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='external_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
    ]
