# Generated by Django 5.1.15 on 2026-03-23 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_alter_resource_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(blank=True, max_length=255, upload_to='resources/%Y/%m/'),
        ),
    ]
