# Generated by Django 5.1.15 on 2026-03-24 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tcc_core', '0002_alter_country_last_updated'),
        ('tcc_data', '0002_newsitem_tradeflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmulatedDataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emulation_strategy', models.CharField(choices=[('static_expert', 'Статические экспертные данные'), ('parametric', 'Параметрическая генерация'), ('historical_based', 'На основе исторических данных'), ('ai_generated', 'AI-генерация')], max_length=20, verbose_name='Стратегия эмуляции')),
                ('base_parameters', models.JSONField(blank=True, default=dict, verbose_name='Базовые параметры')),
                ('variance_config', models.JSONField(blank=True, default=dict, verbose_name='Конфигурация отклонений')),
                ('confidence_level', models.FloatField(default=0.7, verbose_name='Уровень достоверности (0-1)')),
                ('data_age_days', models.IntegerField(default=90, verbose_name='Возраст данных (дней)')),
                ('source_references', models.JSONField(blank=True, default=list, verbose_name='Источники-основания')),
                ('disclaimer_ru', models.TextField(default='Данные эмулированы на основе экспертных оценок и публичных отчётов.', verbose_name='Дисклеймер (RU)')),
                ('last_reviewed', models.DateField(blank=True, null=True, verbose_name='Последний пересмотр')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('data_source', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emulation_config', to='tcc_data.datasource', verbose_name='Источник данных')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Эмулируемый источник',
                'verbose_name_plural': 'Эмулируемые источники',
            },
        ),
        migrations.CreateModel(
            name='EmulatedNodeStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('throughput_percent', models.IntegerField(verbose_name='Загрузка (%)')),
                ('avg_wait_hours', models.FloatField(verbose_name='Среднее ожидание (часы)')),
                ('incidents_count', models.IntegerField(default=0, verbose_name='Инцидентов')),
                ('note', models.TextField(blank=True, verbose_name='Примечание')),
                ('is_emulated', models.BooleanField(default=True, verbose_name='Эмулировано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('emulation_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_statuses', to='tcc_emulator.emulateddatasource', verbose_name='Источник эмуляции')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emulated_statuses', to='tcc_core.routenode', verbose_name='Узел')),
            ],
            options={
                'verbose_name': 'Статус узла (эмуляция)',
                'verbose_name_plural': 'Статусы узлов (эмуляция)',
                'ordering': ['-date'],
                'unique_together': {('node', 'date')},
            },
        ),
    ]
