# Generated by Django 5.1.15 on 2026-03-24 23:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tcc_core', '0002_alter_country_last_updated'),
        ('tcc_data', '0002_newsitem_tradeflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='Рассчитан')),
                ('score_sanctions', models.FloatField(default=0, verbose_name='Скор: санкции')),
                ('score_geopolitical', models.FloatField(default=0, verbose_name='Скор: геополитика')),
                ('score_infrastructure', models.FloatField(default=0, verbose_name='Скор: инфраструктура')),
                ('score_regulatory', models.FloatField(default=0, verbose_name='Скор: регулирование')),
                ('score_financial', models.FloatField(default=0, verbose_name='Скор: финансы')),
                ('score_total', models.FloatField(default=0, verbose_name='Общий скор')),
                ('risk_level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], max_length=20, verbose_name='Уровень риска')),
                ('weights', models.JSONField(default=dict, verbose_name='Веса')),
                ('factors_snapshot', models.JSONField(default=list, verbose_name='Снимок факторов')),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_scores', to='tcc_core.tradecorridor', verbose_name='Коридор')),
            ],
            options={
                'verbose_name': 'Скор маршрута',
                'verbose_name_plural': 'Скоры маршрутов',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='Название')),
                ('plan_code', models.CharField(max_length=10, verbose_name='Код плана')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cost_index', models.FloatField(verbose_name='Индекс стоимости')),
                ('transit_days_min', models.IntegerField(verbose_name='Транзит дней (мин)')),
                ('transit_days_max', models.IntegerField(verbose_name='Транзит дней (макс)')),
                ('reliability_score', models.FloatField(verbose_name='Надёжность (0-1)')),
                ('risk_score', models.FloatField(verbose_name='Риск (0-1)')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('is_recommended', models.BooleanField(default=False, verbose_name='Рекомендован')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('alternative_nodes', models.ManyToManyField(blank=True, to='tcc_core.routenode', verbose_name='Альтернативные узлы')),
                ('corridor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='tcc_core.tradecorridor', verbose_name='Коридор')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Сценарий',
                'verbose_name_plural': 'Сценарии',
                'ordering': ['corridor', 'plan_code'],
            },
        ),
        migrations.CreateModel(
            name='RiskFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_category', models.CharField(choices=[('sanctions', 'Санкции'), ('geopolitical', 'Геополитика'), ('infrastructure', 'Инфраструктура'), ('regulatory', 'Регулирование'), ('financial', 'Финансовый'), ('operational', 'Операционный')], max_length=20, verbose_name='Категория риска')),
                ('severity', models.IntegerField(verbose_name='Серьёзность (1-10)')),
                ('probability', models.IntegerField(verbose_name='Вероятность (1-10)')),
                ('impact_score', models.FloatField(verbose_name='Импакт-скор')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('evidence', models.TextField(blank=True, verbose_name='Доказательства')),
                ('mitigation', models.TextField(blank=True, verbose_name='Меры снижения')),
                ('source_type', models.CharField(choices=[('auto_sanction', 'Авто: санкции'), ('auto_news', 'Авто: новости'), ('auto_worldbank', 'Авто: World Bank'), ('manual_analyst', 'Аналитик TCC')], max_length=20, verbose_name='Тип источника')),
                ('valid_from', models.DateField(verbose_name='Действует с')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действует до')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('corridor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='tcc_core.tradecorridor', verbose_name='Коридор')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='tcc_core.country', verbose_name='Страна')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
                ('news_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_factors', to='tcc_data.newsitem', verbose_name='Новость')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='risk_factors', to='tcc_core.routenode', verbose_name='Узел')),
            ],
            options={
                'verbose_name': 'Риск-фактор',
                'verbose_name_plural': 'Риск-факторы',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['risk_category'], name='tcc_intelli_risk_ca_934a2d_idx'), models.Index(fields=['is_active'], name='tcc_intelli_is_acti_4b4951_idx')],
            },
        ),
    ]
