# Generated by Django 5.1.15 on 2026-03-24 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, max_length=200, verbose_name='Название (EN)')),
                ('iso_code', models.CharField(blank=True, max_length=10, verbose_name='ISO код')),
                ('region_type', models.CharField(choices=[('continent', 'Континент'), ('subcontinent', 'Субконтинент'), ('country', 'Страна'), ('region', 'Регион'), ('city', 'Город')], max_length=20, verbose_name='Тип')),
                ('coordinates', models.JSONField(blank=True, default=dict, verbose_name='Координаты')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tcc_core.region', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso2', models.CharField(max_length=2, unique=True, verbose_name='ISO-2')),
                ('iso3', models.CharField(max_length=3, unique=True, verbose_name='ISO-3')),
                ('name_ru', models.CharField(max_length=200, verbose_name='Название (RU)')),
                ('name_en', models.CharField(max_length=200, verbose_name='Название (EN)')),
                ('wb_stability_index', models.FloatField(blank=True, null=True, verbose_name='World Bank Stability Index')),
                ('ti_cpi_score', models.FloatField(blank=True, null=True, verbose_name='Transparency Int. CPI')),
                ('imf_gdp_growth', models.FloatField(blank=True, null=True, verbose_name='IMF GDP Growth %')),
                ('sanction_risk_level', models.CharField(choices=[('none', 'Нет'), ('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], default='none', max_length=20, verbose_name='Санкционный риск')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='tcc_core.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name_ru'],
            },
        ),
        migrations.CreateModel(
            name='RouteNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название (RU)')),
                ('name_en', models.CharField(blank=True, max_length=300, verbose_name='Название (EN)')),
                ('node_type', models.CharField(choices=[('port_sea', 'Морской порт'), ('port_dry', 'Сухой порт'), ('border', 'Погранпереход'), ('terminal', 'Терминал'), ('railway', 'Ж/д станция'), ('airport', 'Аэропорт'), ('hub', 'Логистический хаб')], max_length=20, verbose_name='Тип узла')),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('capacity_teu_year', models.IntegerField(blank=True, null=True, verbose_name='Мощность (TEU/год)')),
                ('operator', models.CharField(blank=True, max_length=300, verbose_name='Оператор')),
                ('status', models.CharField(choices=[('operational', 'Работает'), ('limited', 'Ограничено'), ('suspended', 'Приостановлен'), ('closed', 'Закрыт')], default='operational', max_length=20, verbose_name='Статус')),
                ('status_note', models.TextField(blank=True, verbose_name='Примечание к статусу')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_emulated', models.BooleanField(default=False, verbose_name='Эмулированные данные')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_nodes', to='tcc_core.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Узел маршрута',
                'verbose_name_plural': 'Узлы маршрутов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CorridorNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('segment_distance_km', models.IntegerField(blank=True, null=True, verbose_name='Расстояние сегмента (км)')),
                ('segment_mode', models.CharField(blank=True, choices=[('rail', 'Ж/д'), ('road', 'Авто'), ('sea', 'Море'), ('ferry', 'Паром'), ('air', 'Авиа'), ('river', 'Река')], max_length=10, verbose_name='Тип транспорта')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridor_memberships', to='tcc_core.routenode', verbose_name='Узел')),
            ],
            options={
                'verbose_name': 'Узел коридора',
                'verbose_name_plural': 'Узлы коридоров',
                'ordering': ['corridor', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TradeCorridor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Описание')),
                ('color', models.CharField(default='#C6A46D', max_length=7, verbose_name='Цвет (hex)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('nodes', models.ManyToManyField(through='tcc_core.CorridorNode', to='tcc_core.routenode', verbose_name='Узлы')),
            ],
            options={
                'verbose_name': 'Торговый коридор',
                'verbose_name_plural': 'Торговые коридоры',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='corridornode',
            name='corridor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corridor_nodes', to='tcc_core.tradecorridor', verbose_name='Коридор'),
        ),
        migrations.AlterUniqueTogether(
            name='corridornode',
            unique_together={('corridor', 'node')},
        ),
    ]
