# Generated by Django 5.1.15 on 2026-03-24 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Обновлено'),
        ),
    ]
