# Generated by Django 5.1.15 on 2026-03-24 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tcc_core', '0002_alter_country_last_updated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код')),
                ('description', models.TextField(verbose_name='Описание')),
                ('sections_config', models.JSONField(blank=True, default=list, verbose_name='Конфигурация секций')),
                ('html_template', models.CharField(default='reports/pdf/base_report.html', max_length=300, verbose_name='HTML шаблон')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Шаблон отчёта',
                'verbose_name_plural': 'Шаблоны отчётов',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Подзаголовок')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('in_review', 'На проверке'), ('approved', 'Утверждён'), ('published', 'Опубликован'), ('archived', 'Архив')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликован')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='Действителен до')),
                ('executive_summary', models.TextField(blank=True, verbose_name='Executive Summary')),
                ('key_findings', models.JSONField(blank=True, default=list, verbose_name='Ключевые выводы')),
                ('recommendations', models.JSONField(blank=True, default=list, verbose_name='Рекомендации')),
                ('is_free_preview', models.BooleanField(default=False, verbose_name='Бесплатный превью')),
                ('preview_text', models.TextField(blank=True, verbose_name='Текст превью')),
                ('price_usd', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена (USD)')),
                ('pdf_file', models.FileField(blank=True, upload_to='reports/pdf/', verbose_name='PDF файл')),
                ('cover_image', models.ImageField(blank=True, upload_to='reports/covers/', verbose_name='Обложка')),
                ('views_count', models.IntegerField(default=0, verbose_name='Просмотры')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='Скачивания')),
                ('corridors', models.ManyToManyField(blank=True, to='tcc_core.tradecorridor', verbose_name='Коридоры')),
                ('countries', models.ManyToManyField(blank=True, to='tcc_core.country', verbose_name='Страны')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_reports', to=settings.AUTH_USER_MODEL, verbose_name='Опубликовал')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_reports', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reports', to='tcc_reports.reporttemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('section_type', models.CharField(choices=[('text', 'Текст'), ('risk_table', 'Таблица рисков'), ('route_score', 'Скор маршрута'), ('scenario_comparison', 'Сравнение сценариев'), ('trade_flow_chart', 'График торговли'), ('sanction_check', 'Санкционная проверка'), ('country_profile', 'Профиль страны'), ('map', 'Карта'), ('custom_chart', 'Произвольный график')], max_length=30, verbose_name='Тип секции')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='Заголовок')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('data_config', models.JSONField(blank=True, default=dict, verbose_name='Конфигурация данных')),
                ('analyst_notes', models.TextField(blank=True, verbose_name='Заметки аналитика')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tcc_reports.report', verbose_name='Отчёт')),
            ],
            options={
                'verbose_name': 'Секция отчёта',
                'verbose_name_plural': 'Секции отчётов',
                'ordering': ['report', 'order'],
            },
        ),
    ]
