# Generated by Django 5.1.15 on 2026-03-24 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('code', models.CharField(max_length=100, unique=True, verbose_name='Код')),
                ('source_type', models.CharField(choices=[('api_public', 'Публичный API'), ('api_private', 'Приватный API (партнёрство)'), ('file_xml', 'XML файл'), ('file_csv', 'CSV файл'), ('rss', 'RSS лента'), ('scraping', 'Парсинг сайта'), ('manual', 'Ручной ввод'), ('emulated', 'Эмуляция')], max_length=20, verbose_name='Тип источника')),
                ('base_url', models.URLField(blank=True, verbose_name='Базовый URL')),
                ('api_key_env', models.CharField(blank=True, max_length=100, verbose_name='ENV переменная API ключа')),
                ('fetch_interval_hours', models.IntegerField(default=24, verbose_name='Интервал обновления (часы)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('access_status', models.CharField(choices=[('available', 'Доступен'), ('pending_partnership', 'Ожидает партнёрства'), ('negotiating', 'На переговорах'), ('emulated', 'Эмулируется'), ('blocked', 'Недоступен')], default='available', max_length=30, verbose_name='Статус доступа')),
                ('last_sync', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация')),
                ('last_sync_status', models.CharField(default='never', max_length=50, verbose_name='Статус последней синхронизации')),
                ('records_count', models.IntegerField(default=0, verbose_name='Записей в базе')),
                ('notes', models.TextField(blank=True, verbose_name='Заметки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
            ],
            options={
                'verbose_name': 'Источник данных',
                'verbose_name_plural': 'Источники данных',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='Начало')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание')),
                ('status', models.CharField(choices=[('running', 'Выполняется'), ('success', 'Успех'), ('partial', 'Частично'), ('failed', 'Ошибка')], max_length=20, verbose_name='Статус')),
                ('records_fetched', models.IntegerField(default=0, verbose_name='Получено записей')),
                ('records_new', models.IntegerField(default=0, verbose_name='Новых записей')),
                ('records_updated', models.IntegerField(default=0, verbose_name='Обновлено записей')),
                ('error_message', models.TextField(blank=True, verbose_name='Сообщение об ошибке')),
                ('celery_task_id', models.CharField(blank=True, max_length=200, verbose_name='Celery Task ID')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='tcc_data.datasource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Лог синхронизации',
                'verbose_name_plural': 'Логи синхронизаций',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SanctionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=200, verbose_name='Внешний ID')),
                ('entity_type', models.CharField(choices=[('individual', 'Физлицо'), ('company', 'Компания'), ('vessel', 'Судно'), ('aircraft', 'Самолёт')], max_length=20, verbose_name='Тип сущности')),
                ('name_primary', models.CharField(max_length=500, verbose_name='Основное имя')),
                ('name_aliases', models.JSONField(blank=True, default=list, verbose_name='Псевдонимы')),
                ('countries', models.JSONField(blank=True, default=list, verbose_name='Страны (ISO2)')),
                ('program', models.CharField(blank=True, max_length=300, verbose_name='Программа санкций')),
                ('listing_date', models.DateField(blank=True, null=True, verbose_name='Дата включения')),
                ('raw_data', models.JSONField(blank=True, default=dict, verbose_name='Сырые данные')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sanction_entries', to='tcc_data.datasource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Санкционная запись',
                'verbose_name_plural': 'Санкционные записи',
                'indexes': [models.Index(fields=['name_primary'], name='tcc_data_sa_name_pr_66f713_idx'), models.Index(fields=['entity_type'], name='tcc_data_sa_entity__e43e80_idx'), models.Index(fields=['is_active'], name='tcc_data_sa_is_acti_44b921_idx')],
                'unique_together': {('source', 'external_id')},
            },
        ),
    ]
