# Generated by Django 5.1.15 on 2026-03-24 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc_core', '0002_alter_country_last_updated'),
        ('tcc_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=500, verbose_name='Внешний ID')),
                ('title', models.CharField(max_length=1000, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('url', models.URLField(blank=True, max_length=2000, verbose_name='URL')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
                ('language', models.CharField(default='en', max_length=10, verbose_name='Язык')),
                ('ai_processed', models.BooleanField(default=False, verbose_name='AI обработано')),
                ('ai_risk_type', models.CharField(blank=True, max_length=100, verbose_name='AI тип риска')),
                ('ai_severity', models.IntegerField(blank=True, null=True, verbose_name='AI серьёзность (1-10)')),
                ('ai_affected_countries', models.JSONField(blank=True, default=list, verbose_name='AI затронутые страны')),
                ('ai_affected_corridors', models.JSONField(blank=True, default=list, verbose_name='AI затронутые коридоры')),
                ('ai_summary_ru', models.TextField(blank=True, verbose_name='AI резюме (RU)')),
                ('ai_is_relevant', models.BooleanField(null=True, verbose_name='AI релевантна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_items', to='tcc_data.datasource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['ai_processed'], name='tcc_data_ne_ai_proc_4ef823_idx'), models.Index(fields=['ai_severity'], name='tcc_data_ne_ai_seve_547e7c_idx')],
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='TradeFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('hs_code', models.CharField(max_length=10, verbose_name='HS код')),
                ('flow_type', models.CharField(choices=[('import', 'Импорт'), ('export', 'Экспорт')], max_length=10, verbose_name='Тип потока')),
                ('value_usd', models.BigIntegerField(verbose_name='Стоимость (USD)')),
                ('weight_kg', models.BigIntegerField(blank=True, null=True, verbose_name='Вес (кг)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('partner_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partner_flows', to='tcc_core.country', verbose_name='Страна-партнёр')),
                ('reporter_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_flows', to='tcc_core.country', verbose_name='Страна-репортёр')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade_flows', to='tcc_data.datasource', verbose_name='Источник')),
            ],
            options={
                'verbose_name': 'Торговый поток',
                'verbose_name_plural': 'Торговые потоки',
                'indexes': [models.Index(fields=['year'], name='tcc_data_tr_year_8ffb68_idx'), models.Index(fields=['hs_code'], name='tcc_data_tr_hs_code_2b2926_idx')],
                'unique_together': {('reporter_country', 'partner_country', 'year', 'hs_code', 'flow_type')},
            },
        ),
    ]
