# Generated by Django 5.1.15 on 2026-04-21 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc_data', '0002_newsitem_tradeflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='full_content',
            field=models.TextField(blank=True, verbose_name='Полный текст статьи'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='groq_affected_nodes',
            field=models.JSONField(blank=True, default=list, help_text="['Актау', 'Баку', 'Хоргос', ...]", verbose_name='Groq: затронутые узлы'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='groq_impact_type',
            field=models.CharField(blank=True, help_text='задержка/инфраструктура/тариф/санкция/объём/прочее', max_length=100, verbose_name='Groq: тип влияния'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='groq_processed',
            field=models.BooleanField(default=False, verbose_name='Groq обработано'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='groq_score',
            field=models.FloatField(blank=True, null=True, verbose_name='Groq: релевантность коридору (0-10)'),
        ),
        migrations.AddField(
            model_name='newsitem',
            name='groq_summary_ru',
            field=models.TextField(blank=True, verbose_name='Groq: вывод на русском'),
        ),
    ]
