# Generated by Django 5.1.15 on 2026-04-21 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tcc_data', '0003_add_groq_analysis_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='base_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='Базовый URL'),
        ),
    ]
