# Generated by Django 5.1.15 on 2026-03-24 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tcc_core', '0002_alter_country_last_updated'),
        ('tcc_intelligence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('risk_change', 'Изменение риска'), ('node_status', 'Статус узла'), ('sanction_update', 'Обновление санкций'), ('score_threshold', 'Порог оценки'), ('news_critical', 'Критические новости')], max_length=50, verbose_name='Тип оповещения')),
                ('severity', models.CharField(choices=[('info', 'Информация'), ('warning', 'Предупреждение'), ('critical', 'Критический')], max_length=20, verbose_name='Серьёзность')),
                ('title', models.CharField(max_length=500, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Решено')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Дополнительные данные')),
                ('corridor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tcc_core.tradecorridor', verbose_name='Коридор')),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tcc_core.country', verbose_name='Страна')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='tcc_core.routenode', verbose_name='Узел маршрута')),
                ('related_score', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alerts', to='tcc_intelligence.routescore', verbose_name='Связанная оценка')),
            ],
            options={
                'verbose_name': 'Оповещение',
                'verbose_name_plural': 'Оповещения',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['alert_type'], name='idx_alert_type'), models.Index(fields=['severity'], name='idx_alert_severity'), models.Index(fields=['is_resolved'], name='idx_alert_resolved')],
            },
        ),
        migrations.CreateModel(
            name='AlertSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_types', models.JSONField(blank=True, default=list, help_text='Список кодов типов оповещений для подписки', verbose_name='Типы оповещений')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email уведомления')),
                ('web_enabled', models.BooleanField(default=True, verbose_name='Web уведомления')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('corridor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to='tcc_core.tradecorridor', verbose_name='Коридор')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_subscriptions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на оповещения',
                'verbose_name_plural': 'Подписки на оповещения',
                'unique_together': {('user', 'corridor')},
            },
        ),
    ]
